 pre_build:
    commands:
      - echo Installing dependencies..
      - yarn --verbose

  build:
    commands:
      - n latest
      - echo Building...
      - yarn build-storybook
      - ls -la
      - ls -la build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
