version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies..
      - yarn --verbose

  build:
    commands:
      - n latest
      - echo Building...
      - yarn run build-storybook
      - ls -la
      - ls -la build
